name = "visclient"
main = ".next/index.js"
compatibility_date = "2023-09-04"

[build]
command = "npm install -g yarn && yarn install --no-immutable && yarn build"

[site]
bucket = ".next"

[build.environment]
NODE_VERSION = "20.18.0" 