name = "visclient"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install -g yarn && yarn install --frozen-lockfile=false && yarn build"
upload.format = "service-worker"

[site]
bucket = ".next"
entry-point = "workers-site"

[build.environment]
NODE_VERSION = "20.18.0" 